Numpy- Indexación en arrays una dimensión

In [2]:
import numpy as np

In [3]:
array = np.arange(0, 10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
array[1]

1

In [6]:
array[-1]

9

In [7]:
array[2:8]

array([2, 3, 4, 5, 6, 7])

In [8]:
array[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
array[:5]

array([0, 1, 2, 3, 4])

In [10]:
array2 = array.copy()

In [13]:
array2[0] = 100
array2

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [12]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Numpy_ indexación en arrays de dos dimensiónes

In [6]:
array3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
array3[0]

array([1, 2, 3])

In [10]:
arrayn = array3[:2]
arrayn

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
array3[0,0]

1

In [12]:
array3[0, 2]

3

In [13]:
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
array3[0, 0]

1

In [16]:
array3[1,1]

5

In [17]:
array3[2,2]

9

In [18]:
#Column
array3[:, 0]

array([1, 4, 7])

In [20]:
array3[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

Numpy - Select elements of an array according to a condition

In [23]:
arrayCondition = np.arange(0, 10)
arrayCondition

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
condition = arrayCondition > 5
condition

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [27]:
arrayCondition[condition]

array([6, 7, 8, 9])

In [29]:
array_greater_than_five =   arrayCondition[condition]
array_greater_than_five

array([6, 7, 8, 9])

In [31]:
arrayCondition[ arrayCondition > 5 ]

array([6, 7, 8, 9])

In [32]:
arrayCondition[ arrayCondition % 2 == 0]

array([0, 2, 4, 6, 8])