Numpy - Array Operations

In [1]:
import numpy as np

In [4]:
array = np.arange(0, 10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
array * 50

array([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450])

In [9]:
array + 40

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [10]:
array - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [12]:
array2 = np.arange(5, 15)
array2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
array + array2

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [14]:
np.sqrt(array2)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [16]:
array2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
np.max(array2)

14